/* NileCore Demos — Shared demo data
   Loaded before gallery.js and coming-soon/app.js so both can use DEMOS. */

const DEMOS = [
  {
    slug: "business-website",
    num: "06",
    name: "Business Website",
    desc: "A full 5-section website for a fictional UAE business — sticky nav, hero, services, testimonials, and a contact form. The demo every client relates to.",
    service: "Business package · 5 pages",
    price: "AED 5,000",
    hours: "12–16 hrs",
    tags: ["HTML", "CSS", "JS"],
    accent: "#00AAEE",
    live: false,
  },
  {
    slug: "analytics-dashboard",
    num: "01",
    name: "Analytics Dashboard",
    desc: "A GA4-style web analytics dashboard — KPI cards, live visitor count, traffic sources chart, top pages table, and geographic breakdown.",
    service: "Included in Business & Professional packages",
    price: "Custom Quote",
    hours: "6–8 hrs",
    tags: ["HTML", "CSS", "SVG"],
    accent: "#00AAEE",
    live: false,
  },
  {
    slug: "ecommerce-store",
    num: "02",
    name: "E-Commerce Store",
    desc: "A working storefront — product grid with filters, add-to-cart with badge animation, sliding cart drawer, and a multi-step checkout flow.",
    service: "E-Commerce add-on",
    price: "+AED 5,000",
    hours: "10–14 hrs",
    tags: ["HTML", "CSS", "JS"],
    accent: "#E8A020",
    live: false,
  },
  {
    slug: "seo-dashboard",
    num: "03",
    name: "SEO Dashboard",
    desc: "An SEO reporting dashboard — site health ring, keyword rankings with trend arrows, Core Web Vitals bars, and a Google Search preview.",
    service: "SEO Keyword Research add-on",
    price: "AED 700",
    hours: "8–10 hrs",
    tags: ["HTML", "CSS", "SVG"],
    accent: "#A855F7",
    live: false,
  },
  {
    slug: "whatsapp-business",
    num: "04",
    name: "WhatsApp Business",
    desc: "A CSS phone mockup showing a WhatsApp Business profile, auto-reply chat conversation, and setup checklist — makes the service instantly clear.",
    service: "WhatsApp Business Setup",
    price: "AED 200",
    hours: "4–6 hrs",
    tags: ["HTML", "CSS"],
    accent: "#25D366",
    live: false,
  },
  {
    slug: "google-business-profile",
    num: "05",
    name: "Google Business Profile",
    desc: "A realistic Google Maps listing preview — business card, star rating, action buttons, photo grid, and a Google Search result snippet.",
    service: "Google Business Setup",
    price: "AED 300",
    hours: "4–5 hrs",
    tags: ["HTML", "CSS"],
    accent: "#4285F4",
    live: false,
  },
  {
    slug: "web-app-dashboard",
    num: "07",
    name: "Web App Dashboard",
    desc: "An enterprise-grade CRM/project portal — fixed sidebar, KPI cards, revenue chart, orders table with status badges, and a live activity feed.",
    service: "Custom Web Application",
    price: "Custom Quote",
    hours: "16–20 hrs",
    tags: ["HTML", "CSS", "JS"],
    accent: "#00AAEE",
    live: false,
  },
  {
    slug: "api-documentation",
    num: "08",
    name: "API Documentation",
    desc: "A Stripe-style API docs page — endpoint list, expandable detail panels, syntax-highlighted JSON, language tabs, and a Try It response preview.",
    service: "REST API Development",
    price: "Custom Quote",
    hours: "5–7 hrs",
    tags: ["HTML", "CSS", "JS"],
    accent: "#A855F7",
    live: false,
  },
];
